name: clang-tidy-review

# You can be more specific, but it currently only works on pull requests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install clang-tidy
      run: |
       sudo apt-get update
       sudo apt-get install -y clang-tidy
       
#     - name: Prepare compile_commands.json
#       run: |
#         cmake ../testing -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - name: clang-tidy review
      uses: ZedThree/clang-tidy-review@v0.4.0
