name: clang-tidy-review

# You can be more specific, but it currently only works on pull requests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Install Dependencies
    - run: |
        sudo add-apt-repository universe
        sudo apt update
        sudo apt-get install build-essential cmake autoconf patch libtool git automake
        sudo apt-get install qtbase5-dev libqt5svg5-dev libqt5opengl5-dev
        sudo apt-get install libeigen3-dev libsqlite3-dev libwildmagic-dev libboost-random1.62-dev \
        libboost-regex1.62-dev libboost-iostreams1.62-dev libboost-date-time1.62-dev libboost-math1.62-dev \
        libxerces-c-dev libglpk-dev zlib1g-dev libsvm-dev libbz2-dev seqan-dev coinor-libcoinmp-dev libhdf5-dev
        
    - name: Building Remaining Dependencies
    - run: |
        git submodule update --init contrib
        cd ..
        mkdir contrib-build
        cd contrib-build
        cmake -DBUILD_TYPE=LIST ../OpenMS/contrib
        cmake -DBUILD_TYPE=WILDMAGIC ../OpenMS/contrib
        cmake -DBUILD_TYPE=EIGEN ../OpenMS/contrib
        cmake -DBUILD_TYPE=ALL -DNUMBER_OF_JOBS=4 ../OpenMS/contrib
    
    - name: Building Openms
    - run: |
        mkdir OpenMS-build
        cd OpenMS-build
        -DCMAKE_PREFIX_PATH="/usr;/usr/local"
        cmake .
        make

    - name: Environment
    - run: |
        export LD_LIBRARY_PATH="/PATH/TO/OpenMS/lib:$LD_LIBRARY_PATH"
        export PATH=$PATH:/PATH/TO/OpenMS/bin
        source ~/.bashrc
    
    - uses: actions/checkout@v2
    
    - name: Install clang-tidy
      run: |
       sudo apt-get update
       sudo apt-get install -y clang-tidy
       
#     - name: Prepare compile_commands.json
#       run: |
#         cmake ../testing -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - name: clang-tidy review
      uses: ZedThree/clang-tidy-review@v0.4.0
