name: clang-tidy-review

# You can be more specific, but it currently only works on pull requests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Optionally generate compile_commands.json

    - uses: ZedThree/clang-tidy-review@v0.7.0
      id: review
      with:
       clang_tidy_checks:  modernize-avoid-bind,
         modernize-deprecated-headers,
         modernize-loop-convert,
         modernize-make-shared,
         modernize-make-unique,
         modernize-pass-by-value,
         modernize-raw-string-literal,
         modernize-redundant-void-arg,
         modernize-replace-auto-ptr,
         modernize-shrink-to-fit,
         modernize-use-auto,
         modernize-use-bool-literals,
         modernize-use-default,
         modernize-use-emplace,
         modernize-use-nullptr,
         modernize-use-override,
         modernize-use-using
    # If there are any comments, fail the check
    - if: steps.review.outputs.total_comments > 3
      run: exit 1
